In [1]:
import numpy as np

In [2]:
np.__version__

'2.4.6'

In [3]:
import sys
sys.version

'3.14.6 | packaged by Anaconda, Inc. | (main, Jul  9 2026, 14:29:05) [MSC v.1942 64 bit (AMD64)]'

# Creating List

In [4]:
ml = [0,1,2,3,4,5]
ml

[0, 1, 2, 3, 4, 5]

In [5]:
type(ml)

list

# List to Array conversion

In [6]:
arr = np.array(ml)

In [8]:
arr

array([0, 1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [11]:
type(ml)

list

In [13]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [18]:
np.arange(20,10) #because of first value is greater

array([], dtype=int64)

In [19]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [20]:
np.arange(10,10)

array([], dtype=int64)

In [23]:
np.arange(1,10,2) #start stop step

array([1, 3, 5, 7, 9])

In [25]:
np.zeros(10) # parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10, dtype = int) #hyperparameter tunning

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((2,2), dtype = int)

array([[0, 0],
       [0, 0]])

In [29]:
zero = np.zeros([2,2])
print(zero)
print('####')
print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [30]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

[[0. 0.]
 [0. 0.]]
####
<class 'numpy.ndarray'>


In [32]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [34]:
np.zeros((10,10), dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [39]:
n = (6,7) # parameter tunning
n1 = (6,8)
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [40]:
print(np.zeros(n,dtype=int)) #hypermeter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [41]:
n

(6, 7)

In [42]:
n1

(6, 8)

In [45]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [46]:
np.ones(3)

array([1., 1., 1.])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [50]:
n

(6, 7)

In [51]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [52]:
#two or three or four is not applicable for numpy

In [53]:
np.ones((6,10),dtype = int) 

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [54]:
np.three((2,4))

AttributeError: module 'numpy' has no attribute 'three'

In [55]:
range(5)

range(0, 5)

In [56]:
r = range(5)
r

range(0, 5)

In [57]:
for i in r:
    print(i)

0
1
2
3
4


In [58]:
list(range(5))

[0, 1, 2, 3, 4]

In [59]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [60]:
rand(2,3)

NameError: name 'rand' is not defined

In [61]:
random.rand(3,5)

NameError: name 'random' is not defined

In [62]:
np.random.rand(1,5)

array([[0.555774  , 0.13108751, 0.38484876, 0.22292138, 0.06229811]])

In [63]:
np.rand(1,10)

AttributeError: module 'numpy' has no attribute 'rand'

In [64]:
np.rand(3)

AttributeError: module 'numpy' has no attribute 'rand'

In [72]:
np.random.rand(3,5)

array([[0.17217455, 0.1827452 , 0.48175274, 0.38420477, 0.57802453],
       [0.11829951, 0.65218233, 0.32171959, 0.2861172 , 0.06982598],
       [0.49347767, 0.22088269, 0.16085207, 0.26667598, 0.34199618]])

In [71]:
np.random.randint(1,5)

4

In [79]:
np.random.randint((1,10,2))

array([0, 3, 1], dtype=int32)

In [81]:
np.random.randint(0,1)

0

In [86]:
np.random.randint(10,20,5)

array([13, 17, 19, 15, 11], dtype=int32)

In [90]:
np.random.randint(1,6,4)

array([3, 5, 2, 1], dtype=int32)

In [92]:
np.random.rand(3)

array([0.95384482, 0.19901889, 0.18120946])

In [95]:
np.random.randint(-30,20,10) 

array([ -9, -10,  13,  19,   0, -25,  15, -17, -14, -10], dtype=int32)

In [97]:
np.random.randint(10,40,(10,10))

array([[36, 17, 31, 18, 35, 18, 23, 38, 16, 30],
       [21, 33, 17, 33, 13, 14, 37, 27, 27, 34],
       [12, 14, 22, 26, 29, 38, 21, 31, 16, 38],
       [34, 31, 19, 31, 16, 12, 23, 31, 20, 34],
       [14, 29, 28, 21, 11, 31, 28, 29, 33, 35],
       [15, 28, 24, 38, 10, 15, 20, 39, 28, 15],
       [18, 27, 27, 22, 31, 19, 27, 33, 13, 12],
       [25, 14, 22, 24, 38, 13, 23, 16, 13, 21],
       [16, 23, 33, 22, 19, 36, 17, 35, 30, 27],
       [19, 27, 13, 12, 14, 31, 14, 23, 22, 12]], dtype=int32)

In [98]:
np.random.randint(1,100,(12,12))

array([[38, 16, 65, 36,  9,  2, 73, 58, 76, 61, 30, 59],
       [25, 43, 31, 36, 44,  2, 78, 64,  8, 99, 55, 11],
       [76, 68, 13, 30, 71,  4, 76, 51, 88, 54, 37, 72],
       [98,  1, 72, 54, 88, 57, 22, 58, 60, 62,  9, 34],
       [61, 21,  8, 70, 40, 59, 59, 24, 14, 17, 64, 68],
       [93, 58, 79, 45, 72, 68, 77, 95, 12,  7, 30,  3],
       [ 3, 96, 71, 47, 22, 99, 81, 72, 88, 98, 11, 20],
       [78, 49, 86,  8, 17, 91, 69, 75, 11, 83, 10, 26],
       [37, 91, 36, 44, 33, 73,  8, 58, 16, 20, 29, 71],
       [17, 27,  4, 62, 28, 84,  1, 21, 21, 45, 41, 91],
       [35, 74, 72, 85, 89, 46, 62,  1, 64, 82, 91, 54],
       [77, 93, 31, 53, 54,  5,  8, 27, 26, 50, 37, 50]], dtype=int32)

In [99]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [105]:
np.arange(1,13).reshape(3,4) # this reshaape means 3 rows and 4 coloum

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# Slicing in matrix


In [110]:
b = np.random.randint(10,20,(5,4))
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [111]:
type(b)

numpy.ndarray

In [112]:
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [113]:
b[:]

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [114]:
b[1:3]

array([[13, 19, 13, 10],
       [12, 10, 11, 11]], dtype=int32)

In [115]:
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [117]:
b[1,2] # this give specific value

np.int32(13)

In [119]:
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [120]:
b[1,3]

np.int32(10)

In [121]:
b[1,-1]

np.int32(10)

In [122]:
b[2,-2]

np.int32(11)

In [123]:
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [124]:
b[2:3]

array([[12, 10, 11, 11]], dtype=int32)

In [128]:
b[2:3]

array([[12, 10, 11, 11]], dtype=int32)

In [130]:
b[1:5]

array([[13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [132]:
b

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [133]:
b[0:-2]

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11]], dtype=int32)

In [134]:
b[0,2]

np.int32(14)

In [135]:
b[-5,-3]

np.int32(17)

In [137]:
b[-5,-2]

np.int32(14)

In [138]:
b[:]

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10],
       [10, 12, 15, 13]], dtype=int32)

In [139]:
b[:-1]

array([[17, 17, 14, 14],
       [13, 19, 13, 10],
       [12, 10, 11, 11],
       [19, 18, 19, 10]], dtype=int32)

In [144]:
b[:,3] # it print only couloum

array([14, 10, 11, 10, 13], dtype=int32)

# Operations

In [145]:
a = np.random.randint(10,20,10)
a

array([10, 11, 11, 16, 11, 12, 19, 14, 18, 18], dtype=int32)

In [146]:
id(a)

2825860482512

In [147]:
arr

array([0, 1, 2, 3, 4, 5])

In [151]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [34, 36, 67, 23, 36, 81, 31, 98, 37, 86],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [152]:
arr

array([0, 1, 2, 3, 4, 5])

In [153]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [154]:
arr[:4]

array([0, 1, 2, 3])

In [155]:
arr2[:]

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [34, 36, 67, 23, 36, 81, 31, 98, 37, 86],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [156]:
arr2[:4]

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52]], dtype=int32)

In [157]:
arr2[0:5]

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86]], dtype=int32)

In [158]:
arr2[1,4]

np.int32(30)

In [159]:
arr2

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [34, 36, 67, 23, 36, 81, 31, 98, 37, 86],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [160]:
arr2[4,5]

np.int32(30)

In [161]:
arr2[-5,-5]

np.int32(97)

In [162]:
arr2[-6,-7]

np.int32(54)

In [163]:
arr[::-1]

array([5, 4, 3, 2, 1, 0])

In [164]:
arr

array([0, 1, 2, 3, 4, 5])

In [165]:
arr2

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80],
       [94, 59, 32, 32, 94, 98, 21,  7, 36, 33],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [34, 36, 67, 23, 36, 81, 31, 98, 37, 86],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [168]:
arr2[::-2] # two steps

array([[82, 66, 44, 77, 69,  9,  3, 94, 16, 40],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [55, 94, 89, 31, 30, 76, 47, 88, 70, 80]], dtype=int32)

In [169]:
arr2[::-3]

array([[82, 66, 44, 77, 69,  9,  3, 94, 16, 40],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [26, 37,  8, 98, 71, 88, 28, 97, 53, 37]], dtype=int32)

In [171]:
arr2[0:10:3]

array([[26, 37,  8, 98, 71, 88, 28, 97, 53, 37],
       [40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [172]:
arr2[3:]

array([[40,  5, 61, 59, 69,  6,  0, 68,  8, 52],
       [31,  6, 75, 54, 76, 30, 84, 74, 52, 86],
       [91, 55, 84, 20,  1, 97, 78, 65, 51, 76],
       [62, 11, 88, 70, 90, 99, 93, 39, 68, 71],
       [16, 57, 17, 66, 14, 38, 20, 52,  1,  3],
       [34, 36, 67, 23, 36, 81, 31, 98, 37, 86],
       [82, 66, 44, 77, 69,  9,  3, 94, 16, 40]], dtype=int32)

In [174]:
arr.max()

np.int64(5)

In [175]:
arr.min()

np.int64(0)

In [176]:
arr

array([0, 1, 2, 3, 4, 5])

In [177]:
arr.mean()

np.float64(2.5)

In [179]:
arr

array([0, 1, 2, 3, 4, 5])

In [180]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [181]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

np.float64(3.0)

# Indexing|

In [182]:
m = np.arange(0,100).reshape(10,10)

In [183]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
row = 4
col = 5

In [185]:
col

5

In [186]:
row

4

In [187]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
m[row,col]

np.int64(45)

In [189]:
m[4,5]

np.int64(45)

In [191]:
m[:,col]

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [192]:
m[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [196]:
m[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [197]:
m[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [198]:
m[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [199]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [200]:
m[1:2,2:4] 

array([[12, 13]])

# Masking

In [201]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [202]:
id(m)

2825882844304

In [204]:
m > 50 #how many numbers are smaller then 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [205]:
m[m==50]

array([50])

In [206]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [207]:
m == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [208]:
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [209]:
a1 = m[m<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [210]:
a1 = m[m>50]
a1

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [211]:
a1 = m[m>=50]
a1

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [213]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 1232


# 1. Array Creation Functions

In [1]:
import numpy as np

In [2]:
# create an array from a list
a = np.array([1,2,3])
print("Array a:", a)

Array a: [1 2 3]


In [6]:
# Create an array with evenly spaced values
b = np.arange(0, 10, 3) # Values from 0 to 10 with step 2
print("Array b:", b)

Array b: [0 3 6 9]


In [7]:
d = np.zeros((2,3))
print("Array d: \n", d)

Array d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [8]:
d = np.zeros((2,3), dtype = int)
print("Array d: \n", d)

Array d: 
 [[0 0 0]
 [0 0 0]]


In [9]:
e = np.zeros((3,2))
print("Array d: \n", e)

Array d: 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
d = np.eye(5)
print("Identity Matrix f:\n", d)

Identity Matrix f:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# 2. Array Manipulation Functions

In [52]:
# reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1, (1,3)) # reshaped 1x5
print("reshape matrix:", reshaped)

reshape matrix: [[1 2 3]]


In [53]:
a1 = np.array([1,2,3,4,5])
reshaped = np.reshape(a1, (5,1)) # reshaped 1x5
print("reshape matrix:", reshaped)

reshape matrix: [[1]
 [2]
 [3]
 [4]
 [5]]


In [54]:
#flattened an array
b1 = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
flattened = np.ravel(b1) #flattened in 1D array
print("Flattened array:", flattened)

Flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [55]:
c1 = np.array([[1,2], [3,4], [5,6], ])
transposed = np.transpose(c1)  # transpose the array
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3 5]
 [2 4 6]]


In [56]:
a2 = np.array([1,2])
b2 = np.array([3,4]) # this can arrange as vertically
stacked = np.vstack([a2,b2]) # Stack a and b vertically
print("Stacked array:\n", stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [57]:
a2 = np.array([1,2])
b2 = np.array([3,4]) # this can arrange as horizontal
stacked = np.hstack([a2,b2]) # Stack a and b horizontal
print("Stacked array:\n", stacked)

Stacked array:
 [1 2 3 4]


# mathematical function

In [58]:
# add two array
g = np.array([1,2,3,4,5])
added= np.add(g, 2) # add 2 to each element
print("added 2 to g:" ,added)

added 2 to g: [3 4 5 6 7]


In [59]:
g

array([1, 2, 3, 4, 5])

In [60]:
# square each element
squared = np.power(g, 2)
print("squared g:", squared)

squared g: [ 1  4  9 16 25]


In [61]:
# now square root of each element √
sv = np.sqrt(g) # square root of each element
print("square root of g:", sv)


square root of g: [1.         1.41421356 1.73205081 2.         2.23606798]


In [62]:
print(a)
print(g)

[1 2 3]
[1 2 3 4 5]


In [63]:
a3 = np.array([1, 2, 3]) #because in dot product both a and g has to same in values means in length
d_p= np.dot(a, g) # Dot product of a and g
print("Dot product of a1 and a: ", d_p)

ValueError: shapes (3,) and (5,) not aligned: 3 (dim 0) != 5 (dim 0)

In [69]:
a1 = [1,2,3]
a1

[1, 2, 3]

In [70]:
print(a)
print(a1)

[1 2 3]
[1, 2, 3]


In [71]:
a = [1,2,3]
a

[1, 2, 3]

In [73]:
print(a)
print(a1)

[1, 2, 3]
[1, 2, 3]


In [74]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# Statistical math

In [77]:
s = np.array([1,2,3,4]) # find mean value of given array
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [78]:
# Standard Deviation of an array
var = np.var(s)
print("Variance of s : ", var)

Variance of s :  1.25


In [80]:
std_dev = np.std(d)
print("Standard Deviation of s:", std_dev)

Standard Deviation of s: 0.4


In [81]:
s

array([1, 2, 3, 4])

In [84]:
# minimum element of an array
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [85]:
maximum = np.max(s)
print("max of s:", maximum)

max of s: 4


# Linear Algebra Functions

In [86]:
matrix = np.array([[1,2], [3,4], [5,6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

# Random Sampling Function

In [89]:
r_v = np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:", r_v) 

Random values: [0.75722447 0.61318597 0.04027119]


In [94]:
# Set seed for reproducibility
np.random.seed(0) # this give constant value which can not be changed
# Generate random values between 0 and 1
r_v = np.random.rand(3)
print("Random values:", r_v) 

Random values: [0.5488135  0.71518937 0.60276338]


In [98]:
# Generate random integer
r_i = np.random.randint(0, 10, size=4) # random integer between 0 and 10
print("Random integer:", r_i)

Random integer: [6 8 8 1]


In [101]:
np.random.seed(0) # by this cannot change the value
r_i = np.random.randint(0, 10, size=4) # random integer between 0 and 10
print("Random integer:", r_i)

Random integer: [5 0 3 3]


# Boolean and logical function

In [102]:
# Check if all element  are True 
# all
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) # checl if all are true
print("All elements True:", all_true)

All elements True: False


In [103]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [107]:
# Check if all elements are True
logical_test = np.array([False, True, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [109]:
# Check if any elements are True
# any
# atleat one is True it passess True
any_true = np.any(logical_test)
print("Any Element are True:", any_true)

Any Element are True: True


# # Intersection of two arrays


In [110]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [111]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# Attribute Array Function

In [113]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


# Other Functions

In [118]:
a = np.array([1,2,3,4,5])
copied_array = np.copy(a)
print("Copied array:", copied_array)

Copied array: [1 2 3 4 5]


In [120]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes) # it add 8bytes in ever given value thats why 5x8 = 40

Size of a in bytes: 40


In [121]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
