In [1]:
import numpy as np

In [2]:
a= np.array([1,2,3])
print("Array a:", a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,3)
print("array b:", b)

array b: [0 3 6 9]


In [6]:
d = np.zeros((2,3))
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
d = np.zeros((2,3), dtype = int)
print("Array d:\n", d)

Array d:
 [[0 0 0]
 [0 0 0]]


In [8]:
e = np.ones((3,2))
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
f = np.eye(4) # Identical matrix
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 2.Array manipulation  function

# 

In [13]:
a1  = np.array([1,2,3])
reshape = np.reshape(a1,(1,3))
print("reshape array1:\n", a1)

reshape array1:
 [1 2 3]


In [15]:
a1  = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("Reshaped array1:", reshaped)

Reshaped array1: [[1]
 [2]
 [3]]


In [20]:
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print("Flattened array:\n",flattened)

Flattened array:
 [ 1  2  3  4  5  6  7  8  9 10]


In [23]:
e1 = np.array([[1,2],[3,4]])
transposed = np.transpose(e1)
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [36]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2]) # vertical stacked
print("Stacked array:\n", stacked)


Stacked array:
 [[1 2]
 [3 4]]


In [37]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2]) #hhorizontal stack
print("Stacked array:\n", stacked)

Stacked array:
 [1 2 3 4]


# math operation in numpy

In [38]:
g = np.array([1,2,3,4])
added = np.add(g,2)
print("added 2 to g :", added)

added 2 to g : [3 4 5 6]


In [39]:
squared = np.power(g,2)
print("squared g:", squared)

squared g: [ 1  4  9 16]


In [40]:
sqrt_val = np.sqrt(g)
print("square root of g:", sqrt_val)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [41]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [43]:
a3 = np.array([1,2,3])
dot_product = np.dot(a,g) #dot product requied same dimnentiyon
print("dot product of a1 and a:",dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [44]:
a3 = np.array([1,2,3])
dot_product = np.dot(a1,a) #dot product requied same dimnentiyon
print("dot product of a1 and a:",dot_product)

dot product of a1 and a: 14


# statistical mathematics

In [45]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Measn of s;", mean)

Measn of s; 2.5


In [46]:
var = np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [47]:
std_dev = np.std(s)
print("standred deviation of s:", std_dev)

standred deviation of s: 1.118033988749895


In [48]:
s

array([1, 2, 3, 4])

In [50]:
#minimum value and maximum value

# 5. Linear algebra Functions

In [51]:
matrix = np.array([[1,2]])
matrix

array([[1, 2]])

# random sampling function

In [52]:
random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.02811153 0.448577   0.09667679]


In [69]:
np.random.seed(0)

random_vals = np.random.rand(3)
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [70]:
rand_ints = np.random.randint(0,10, size = 4)
print("random integer:", rand_ints)

random integer: [3 7 9 3]


In [75]:
np.random.seed(0)

rand_ints = np.random.randint(0,10, size=5)
print("random integer:", rand_ints)

random integer: [5 0 3 3 7]


# Boolean and logical function